import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'

type RouteParams = { params: Promise<{ id: string }> }

export async function GET(
  request: NextRequest,
  context: RouteParams
) {
  try {
    const params = await context.params
    const { searchParams } = new URL(request.url)
    const format = searchParams.get('format') || 'pdf'
    const reportId = params.id

    // Mock report data - in real implementation, fetch from database
    const mockReportData = {
      id: reportId,
      title: `Report ${reportId}`,
      type: 'Sales Report',
      description: 'Monthly sales performance report',
      data: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
        datasets: [
          {
            label: 'Sales',
            data: [12000, 19000, 3000, 5000, 2000, 3000],
            backgroundColor: 'rgba(59, 130, 246, 0.5)',
          },
        ],
      },
      createdAt: new Date().toISOString(),
      user: {
        firstName: 'John',
        lastName: 'Doe',
      },
    }

    if (format === 'pdf') {
      // Generate PDF content
      const pdfContent = generatePDFContent(mockReportData)
      
      return new NextResponse(pdfContent as any, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="report-${reportId}.pdf"`,
        },
      })
    } else if (format === 'excel') {
      // Generate Excel content
      const excelContent = generateExcelContent(mockReportData)
      
      return new NextResponse(excelContent as any, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="report-${reportId}.xlsx"`,
        },
      })
    } else {
      return NextResponse.json(
        { error: 'Invalid format. Supported formats: pdf, excel' },
        { status: 400 }
      )
    }
  } catch (error) {
    console.error('Error exporting report:', error)
    return NextResponse.json(
      { error: 'Failed to export report' },
      { status: 500 }
    )
  }
}

function generatePDFContent(reportData: any): Buffer {
  // Simple PDF generation - in real implementation, use a proper PDF library
  const pdfContent = `
%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length 200
>>
stream
BT
/F1 12 Tf
72 720 Td
(${reportData.title}) Tj
0 -20 Td
(${reportData.description}) Tj
0 -20 Td
(Generated on: ${new Date(reportData.createdAt).toLocaleDateString()}) Tj
0 -20 Td
(Generated by: ${reportData.user.firstName} ${reportData.user.lastName}) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000274 00000 n 
0000000525 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
612
%%EOF
  `
  
  return Buffer.from(pdfContent, 'utf-8')
}

function generateExcelContent(reportData: any): Buffer {
  // Simple Excel generation - in real implementation, use a proper Excel library
  const excelContent = `
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>${reportData.title}</Title>
  <Author>${reportData.user.firstName} ${reportData.user.lastName}</Author>
  <Created>${new Date(reportData.createdAt).toISOString()}</Created>
 </DocumentProperties>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s62">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#000000" ss:Bold="1"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Sheet1">
  <Table ss:ExpandedColumnCount="2" ss:ExpandedRowCount="10" x:FullColumns="1" x:FullRows="1">
   <Column ss:AutoFitWidth="0" ss:Width="200"/>
   <Column ss:AutoFitWidth="0" ss:Width="100"/>
   <Row>
    <Cell ss:StyleID="s62"><Data ss:Type="String">${reportData.title}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">${reportData.description}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Generated on: ${new Date(reportData.createdAt).toLocaleDateString()}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Generated by: ${reportData.user.firstName} ${reportData.user.lastName}</Data></Cell>
   </Row>
   <Row>
    <Cell ss:StyleID="s62"><Data ss:Type="String">Month</Data></Cell>
    <Cell ss:StyleID="s62"><Data ss:Type="String">Sales</Data></Cell>
   </Row>
   ${reportData.data.labels.map((label: string, index: number) => `
   <Row>
    <Cell><Data ss:Type="String">${label}</Data></Cell>
    <Cell><Data ss:Type="Number">${reportData.data.datasets[0].data[index]}</Data></Cell>
   </Row>
   `).join('')}
  </Table>
 </Worksheet>
</Workbook>
  `
  
  return Buffer.from(excelContent, 'utf-8')
}










